Update Jenkinsfile

diff --git a/API Testing/Jenkinsfile b/API Testing/Jenkinsfile
--- a/API Testing/Jenkinsfile
+++ b/API Testing/Jenkinsfile
@@ -17,10 +17,17 @@ pipeline {
         stage('Run API Tests with Newman') {
             steps {
                 echo 'Running API Tests with Newman...'
-                withEnv(["PATH=${env.NODE_HOME}:${env.PATH}"]) {
-                    executable "${env.NEWMAN_HOME}\\newman.cmd"
-                    args "run", "Demoblaze API Tests.postman_collection.json"
-                }
+                bat """
+                    set PATH="${NODE_HOME};%PATH%"
+                    echo "Current PATH: %PATH%"
+                    IF EXIST "%NODE_HOME%\\node.exe" (
+                        echo "Node.js executable found."
+                        "%NODE_HOME%\\node.exe" "${NEWMAN_HOME}\\newman.cmd" run "Demoblaze API Tests.postman_collection.json"
+                    ) ELSE (
+                        echo "Node.js executable NOT found at %NODE_HOME%."
+                        exit 1
+                    )
+                """
             }
         }
 
